name: Build Seko Tweak

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Theos and SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* $HOME/theos/sdks/
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Package
        run: |
          export THEOS=$HOME/theos
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Seko-Tweak-Deb
          path: packages/*.deb


          
