name: Build DEB Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build deb package
        run: |
          chmod -R 755 DEBIAN
          dpkg-deb --build . my-tweak.deb
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tweak-deb
          path: my-tweak.deb
          
